# Amazon SageMaker Autopilot Data Exploration Report

This report contains insights about the dataset you provided as input to the AutoML job.
This data report was generated by **automl-dm-30-15-44-36** AutoML job.
To check for any issues with your data and possible improvements that can be made to it,
consult the sections below for guidance.
You can use information about the predictive power of each feature in the **Data Sample** section and
from the correlation matrix in the **Cross Column Statistics** section to help select a subset of the data
that is most significant for making predictions.

**Note**: SageMaker Autopilot data reports are subject to change and updates.
It is not recommended to parse the report using automated tools, as they may be impacted by such changes.

## Dataset Summary
**Note**: due to timeouts while processing your data, it's possible that some issues with your data were not detected.
See further details in the sections below. To avoid such timeouts, try reducing the number of columns in the dataset.



<br>
<b>Dataset Properties</b>
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Rows</th>
      <th>Columns</th>
      <th>Duplicate rows</th>
      <th>Target column</th>
      <th>Missing feature values</th>
      <th>Invalid feature values</th>
      <th>Detected problem type</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>31005</td>
      <td>2</td>
      <td>0.83%</td>
      <td>star_rating</td>
      <td>0.01%</td>
      <td>0.01%</td>
      <td>MulticlassClassification</td>
    </tr>
  </tbody>
</table>
</div>
<b>Detected Column Types</b>
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Numeric</th>
      <th>Categorical</th>
      <th>Text</th>
      <th>Datetime</th>
      <th>Sequence</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Column Count</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>Percentage</th>
      <td>0.00%</td>
      <td>0.00%</td>
      <td>100.00%</td>
      <td>0.00%</td>
      <td>0.00%</td>
    </tr>
  </tbody>
</table>
</div>

---

## Report Contents

1. [Target Analysis](#Target-Analysis)<br>
1. [Data Sample](#Data-Sample)<br>
1. [Feature Summary](#Feature-Summary)<br>
1. [Duplicate Rows](#Duplicate-Rows)<br>
1. [Cross Column Statistics](#Cross-Column-Statistics)<br>
1. [Anomalous Rows](#Anomalous-Rows)<br>
1. [Missing Values](#Missing-Values)<br>
1. [Cardinality](#Cardinality)<br>
1. [Descriptive Stats](#Descriptive-Stats)<br>
1. [Definitions](#Definitions)<br>
---

### Target Analysis



The column **star_rating** is used as the target column.
See the distribution of values (labels) in the target column below:

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>Number of Classes</th>
      <th>Invalid Percentage</th>
      <th>Missing Percentage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>5</td>
      <td>0.00%</td>
      <td>0.00%</td>
    </tr>
  </tbody>
</table>
</div>
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>Target Label</th>
      <th>Frequency Percentage</th>
      <th>Label Count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>3</td>
      <td>20.00%</td>
      <td>6201</td>
    </tr>
    <tr>
      <td>2</td>
      <td>20.00%</td>
      <td>6201</td>
    </tr>
    <tr>
      <td>4</td>
      <td>20.00%</td>
      <td>6201</td>
    </tr>
    <tr>
      <td>5</td>
      <td>20.00%</td>
      <td>6201</td>
    </tr>
    <tr>
      <td>1</td>
      <td>20.00%</td>
      <td>6201</td>
    </tr>
  </tbody>
</table>
</div>

<center><figure>
  <img src="" style="height: 250px; width: auto;">
  <figcaption>Histogram of the target column labels.</figcaption>
</figure></center>

## Data Sample

The following table contains a random sample of **10** rows from the dataset.
The top two rows provide the type and prediction power of each column.
Verify the input headers correctly align with the columns of the dataset sample.
If they are incorrect, update the header names of your input dataset in Amazon Simple Storage Service (Amazon S3).

<div style="overflow-y:auto;">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th></th>
      <th>star_rating</th>
      <th>review_body</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Prediction Power</th>
      <td>-</td>
      <td>0.204274</td>
    </tr>
    <tr>
      <th>Column Types</th>
      <td>-</td>
      <td>text</td>
    </tr>
    <tr>
      <th>27230</th>
      <td>1</td>
      <td>It was not formated for my computer and cannot use it.  The program i need to ad to use this product by reading reviews about the lion it will mess my mac computer up.  Could shut it down and run slower&lt;br /&gt;I just need to get a QB2011 to download to my Dell Computer.  Because I am treasurer of a National Organization and I need to review the pages of bookkeeping each month, and still can not due with QB Mac 2013. Its been a long process. and found out about the Lion today.&lt;br /&gt;&lt;br /&gt;Paulet...</td>
    </tr>
    <tr>
      <th>19121</th>
      <td>1</td>
      <td>I was under the impression that this would be easy to use; maybe for some, but not for others I suppose.  I first had issues connecting to my bank the first day I purchased it after entering all my bills with due dates.  I took a break out of frustration, not being able to connect to my bank, and ran into the same problems two months later. Finally the connection to the bank was successful, however changing the due dates had to be done for each one and somehow I ran into duplicates, some say...</td>
    </tr>
    <tr>
      <th>1043</th>
      <td>3</td>
      <td>It's still broken. Immediately EXITS when you try to synchronize it with any of the financial institutions. None of the &amp;#34;fixes&amp;#34; on the forum works either... not real happy about this but it's not a show-stopper...</td>
    </tr>
    <tr>
      <th>7801</th>
      <td>2</td>
      <td>They advertise that you can transfer information from the previous year's return from H&amp;R Block.  After my frustrations with using H&amp;R Block to do my 2012 taxes I thought I'd go with (the more expensive) TurboTax this year.  However, it refuses to transfer my data so I will be forced to enter all of it manually, including depreciation information.  This is very frustrating!  I am using the Mac version.</td>
    </tr>
    <tr>
      <th>30479</th>
      <td>5</td>
      <td>I had absolutely no problems downloading and installing TurboTax Premier on Windows 8.1.  The Premier version had everything that I needed as a home owner.  The process of competing my tax forms was simple and very easy to understand.  Based on other reviews about the cost of TurboTax, I almost purchased H&amp;R Block, but I've been an H&amp;R Block user previously, and I think H&amp;R Block is less user friendly than TurboTax.  Since I got the Prime member discount on the Premier version, it was less c...</td>
    </tr>
    <tr>
      <th>22946</th>
      <td>5</td>
      <td>This it's the perfect protection that me and my family needs.  Amazon offers great deals on virus protection, and you can't go wrong with Norton's 360 protection service for the price.  I thoroughly enjoy knowing that my computer is safe when I'm working or just browsing the Internet.  This it's a Best Buy.</td>
    </tr>
    <tr>
      <th>9242</th>
      <td>2</td>
      <td>n8ice concept but does not work on windows 8.. not sure if this is related or not but after installing this product my laptop crashed and i have been unable to use it since..</td>
    </tr>
    <tr>
      <th>21581</th>
      <td>1</td>
      <td>So much is wrong, see the other reviews, I don't have time to waste as I need to get this stinking pile of dung of my system and re-install 2010 if I can.</td>
    </tr>
  </tbody>
</table>
</div>
<div style="overflow-x:auto;">

## Feature Summary


Prediction power is measured by stratified splitting the data into 80%/20% training and validation folds. We fit a
model for each feature separately on the training fold after applying minimal feature pre-processing and measure
prediction performance on the validation data. Higher prediction power scores, toward 1, indicate columns that are
more useful for predicting the target on their own. Lower scores, toward 0 point to columns that contain little useful
information for predicting the target on their own.
<center><figure>
<img src="" style="height: 350px; width: auto;">
</figure></center>

## Duplicate Rows


<div class="alert alert-secondary"> ⚠️ <strong> Low severity insight: “Duplicate rows” </strong> <br>
0.83% of the rows were found to be duplicates when testing a random sample of 10000 rows from the dataset. Some data sources could include valid duplicates, but in some cases these duplicates could point to problems in data collection. Unintended duplicate rows could disrupt the automatic hyperparameter tuning of Amazon SageMaker Autopilot and result in sub-par model. Thus should be removed for more accurate results. This preprocessing can be done with Amazon SageMaker Data Wrangler using the “Drop duplicates” transform under “Manage rows”.
</div>

A sample of duplicate rows is presented below.
The number of occurrences of a row is given in left most **Duplicate count** column.
<div style="overflow-y:auto;">
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: left;">
      <th>Duplicate count</th>
      <th>review_body</th>
      <th>star_rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>6</td>
      <td>Excellent</td>
      <td>5</td>
    </tr>
    <tr>
      <td>5</td>
      <td>ok</td>
      <td>3</td>
    </tr>
    <tr>
      <td>5</td>
      <td>Good</td>
      <td>4</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Good</td>
      <td>5</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Great</td>
      <td>5</td>
    </tr>
    <tr>
      <td>3</td>
      <td>For some reason I couldn't get it to work.</td>
      <td>2</td>
    </tr>
    <tr>
      <td>3</td>
      <td>As expected</td>
      <td>5</td>
    </tr>
    <tr>
      <td>3</td>
      <td>okay</td>
      <td>4</td>
    </tr>
    <tr>
      <td>3</td>
      <td>good</td>
      <td>3</td>
    </tr>
    <tr>
      <td>3</td>
      <td>good</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>
<div style="overflow-x:auto;">

## Cross Column Statistics

Amazon SageMaker Autopilot calculates Pearson’s correlation between columns in your dataset.
Removing highly correlated columns can reduce overfitting and training time.
Pearson’s correlation is in the range [-1, 1] where 0 implies no correlation, 1 implies perfect correlation,
and -1 implies perfect inverse correlation.

No correlation scores were calculated because the calculation took too long to complete.

### Anomalous Rows

Anomalous rows are detected using the Isolation forest algorithm on a sample of
**10000**
randomly chosen
rows after basic preprocessing. The isolation forest algorithm associates an anomaly score to each row of the dataset
it is trained on. Rows with negative anomaly scores are usually considered anomalous and rows with positive anomaly
scores are considered non-anomalous. When investigating an anomalous row, look for any unusual values -
in particular any that might have resulted from errors in the gathering and processing of data.
Deciphering whether a row is indeed anomalous, contains errors, or is in fact valid requires domain knowledge and
application of business logic.

There were no anomalous rows found in the dataset.

### Missing Values
Within the data sample, the following columns contained missing values, such as: `nan`, white spaces, or empty fields.

SageMaker Autopilot will attempt to fill in missing values using various techniques. For example,
missing values can be replaced with a new 'unknown' category for `Categorical` features
and missing `Numerical` values can be replaced with the **mean** or **median** of the column.

We found **1 of the 2** of the columns contained missing values.
The following table shows the **1** columns with the highest percentage of missing values.

<div class="alert alert-info"> 💡 <strong> Suggested Action Items</strong>
- Investigate the governance of the training dataset. Do you expect this many missing values?
    Are you able to fill in the missing values with real data?
- Use domain knowledge to define an appropriate default value for the feature. Either:
    - Replace all missing values with the new default value in your dataset in Amazon S3.
    - Add a step to the feature pre-processing pipeline to fill missing values, for example with a
    [sklearn.impute.SimpleImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html).
</div>

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>% of Missing Values</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>review_body</th>
      <td>0.01%</td>
    </tr>
  </tbody>
</table>
</div>

### Cardinality
For `String` features, it is important to count the number of unique values to determine whether to treat a feature as `Categorical` or `Text`
and then processes the feature according to its type.

For example, SageMaker Autopilot counts the number of unique entries and the number of unique words.
The following string column would have **3** total entries, **2** unique entries, and **3** unique words.

|       | String Column     |
|-------|-------------------|
| **0** | "red blue"        |
| **1** | "red blue"        |
| **2** | "red blue yellow" |

If the feature is `Categorical`, SageMaker Autopilot can look at the total number of unique entries and transform it using techniques such as one-hot encoding.
If the field contains a `Text` string, we look at the number of unique words, or the vocabulary size, in the string.
We can use the unique words to then compute text-based features, such as Term Frequency-Inverse Document Frequency (tf-idf).

**Note:** If the number of unique values is too high, we risk data transformations expanding the dataset to too many features.
In that case, SageMaker Autopilot will attempt to reduce the dimensionality of the post-processed data,
such as by capping the number vocabulary words for tf-idf, applying Principle Component Analysis (PCA), or other dimensionality reduction techniques.

The table below shows **2 of the 2** columns ranked by the number of unique entries.

<div class="alert alert-info"> 💡 <strong> Suggested Action Items</strong>

- Verify the number of unique values of a feature is as expected.
    One explanation for unexpected number of unique values could be multiple encodings of a value.
    For example `US` and `U.S.` will count as two different words.
    You could correct the error at the data source or pre-process your dataset in your S3 bucket.
- If the number of unique values seems too high for Categorical variables,
    investigate if multiple unique values can be grouped into a smaller set of possible values.
</div>

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Number of Unique Entries</th>
      <th>Number of Unique Words (if Text)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>star_rating</th>
      <td>5</td>
      <td>n/a</td>
    </tr>
    <tr>
      <th>review_body</th>
      <td>30504</td>
      <td>93555</td>
    </tr>
  </tbody>
</table>
</div>

### Descriptive Stats
For each of the input features that has at least one numeric value, several descriptive statistics are computed from the data sample.

SageMaker Autopilot may treat numerical features as `Categorical` if the number of unique entries is sufficiently low.
For `Numerical` features, we may apply numerical transformations such as normalization, log and quantile transforms,
and binning to manage outlier values and difference in feature scales.

We found **1 of the 2** columns contained at least one numerical value.
The table below shows the **1** columns which have the largest percentage of numerical values.
Percentage of outliers is calculated only for columns which Autopilot detected to be of numeric type. Percentage of outliers is
not calculated for the target column.

<div class="alert alert-info"> 💡 <strong> Suggested Action Items</strong>

- Investigate the origin of the data field. Are some values non-finite (e.g. infinity, nan)?
    Are they missing or is it an error in data input?
- Missing and extreme values may indicate a bug in the data collection process.
    Verify the numerical descriptions align with expectations.
    For example, use domain knowledge to check that the range of values for a feature meets with expectations.
</div>


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>% of Numerical Values</th>
      <th>Mean</th>
      <th>Median</th>
      <th>Min</th>
      <th>Max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>star_rating</th>
      <td>100.0%</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>1.0</td>
      <td>5.0</td>
    </tr>
  </tbody>
</table>
</div>

## Definitions

### Feature types

**Numeric:** Numeric values, either floats or integers. For example: age, income. When training a machine learning model, it is assumed that numeric values are ordered and a distance is defined between them. For example, 3 is closer to 4 than to 10 and 3 < 4 < 10.

**Categorical:** The column entries belong to a set of unique values that is usually much smaller than number of rows in the dataset. For example, a column from datasets with 100 rows with the unique values "Dog", "Cat" and "Mouse". The values could be numeric, textual, or combination of both. For example, "Horse", "House", 8, "Love" and 3.1 are
all valid values and can be found in the same categorical column. When manipulating column of categorical values, a machine learning model does not assume that they are ordered or that distance function is defined on them, even if all of the values are numbers.

**Binary:** A special case of categorical column for which the cardinality of the set of unique values is 2.

**Text:** A text column that contains many non-numeric unique values, often a human readable text. In extreme cases, all the elements of the column are unique, so no two entries are the same.

**Datetime:** This column contains date and/or time information.

### Feature statistics

**Prediction power:** Prediction power of a column (feature) is a measure of how useful it is for predicting the target variable. It is measured using a stratified split into 80%/20% training and validation folds. We fit a model for each feature separately on the training fold after applying minimal feature pre-processing and measure prediction performance on the validation data. The scores are normalized to the range [0,1]. A higher prediction power score near 1 indicate that a column is more useful for predicting the target on its own. A lower score near 0 indicate that a column contains little useful information for predicting the target on their own. Although it is possible that a column that is uninformative on its own can be useful in predicting the target when used in tandem with other features, a low score usually indicates the feature is redundant. A score of 1 implies perfect predictive abilities, which often indicates an error called target leakage. The cause is typically a column present in dataset that is hard or impossible to obtain at prediction time, such as a duplicate of the target.

**Outliers:** Outliers are detected using two statistics that are robust to outliers: median and robust standard deviation (RSTD). RSTD is derived by clipping the feature values to the range [5 percentile, 95 percentile] and calculating the standard deviation of the clipped vector. All values larger than median + 5 * RSTD or smaller than median - 5 * RSTD are considered to be outliers.

**Skew:** Skew measures the symmetry of the distribution and is defined as the third moment of the distribution divided by the third power of the standard deviation. The skewness of the normal distribution or any other symmetric distribution is zero. Positive values imply that the right tail of the distribution is longer than the left tail. Negative values imply that the left tail of the distribution is longer than the right tail. As a thumb rule, a distribution is considered skewed when the absolute value of the skew is larger than 3.

**Kurtosis:** Pearson's kurtosis measures the heaviness of the tail of the distribution and is defined as the fourth moment of the distribution divided by the fourth power of the standard deviation. The kurtosis of the normal distribution is 3. Thus, kurtosis values lower than 3 imply that the distribution is more concentrated around the mean and the tails are lighter than the tails of the normal distribution. Kurtosis values higher than 3 imply heavier tails than the normal distribution or that the data contains outliers.

**Missing Values:** Empty strings and strings composed of only white spaces are considered missing.

**Valid values:**

* **Numeric features / regression target:** All values that could be casted to finite floats are valid. Missing values are not valid.
* **Categorical / binary / text features / classification target:** All values that are not missing are valid.
* **Datetime features:** All values that could be casted to datetime object are valid. Missing values are not valid.

**Invalid values:** values that are either missing or that could not be casted to the desired type. See the definition of valid values for more information