# NOTE:  THIS NOTEBOOK WILL TAKE A 30 MINUTES TO COMPLETE.

# PLEASE BE PATIENT.

# Optimize Models using Automatic Model Tuning

<img src="img/hpt.png" width="90%" align="left">

In [1]:
import boto3
import sagemaker
import pandas as pd

sess = sagemaker.Session()
bucket = sess.default_bucket()
role = sagemaker.get_execution_role()
region = boto3.Session().region_name

sm = boto3.Session().client(service_name="sagemaker", region_name=region)

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

# PRE-REQUISITE: _You need to have succesfully run the notebooks in the `PREPARE`section before you continue with this notebook._

# Specify the S3 Location of the Features

In [2]:
%store -r processed_train_data_s3_uri

In [3]:
try:
    processed_train_data_s3_uri
    print("[OK]")
except NameError:
    print("+++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the PREPARE section before you continue.")
    print("+++++++++++++++++++++++++++++++")

[OK]

In [4]:
print(processed_train_data_s3_uri)

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train

In [5]:
%store -r processed_validation_data_s3_uri

In [6]:
try:
    processed_validation_data_s3_uri
    print("[OK]")
except NameError:
    print("+++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the previous sections before you continue.")
    print("+++++++++++++++++++++++++++++++")

[OK]

In [7]:
print(processed_validation_data_s3_uri)

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation

In [8]:
%store -r processed_test_data_s3_uri

In [9]:
try:
    processed_test_data_s3_uri
    print("[OK]")
except NameError:
    print("+++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the previous sections before you continue.")
    print("+++++++++++++++++++++++++++++++")

[OK]

In [10]:
print(processed_test_data_s3_uri)

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test

In [11]:
print(processed_train_data_s3_uri)
!aws s3 ls $processed_train_data_s3_uri/

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train
2024-07-01 23:00:11   10472476 part-algo-1-amazon_reviews_us_Digital_Software_v1_00.tfrecord
2024-07-01 23:00:11    2313178 part-algo-1-amazon_reviews_us_Gift_Card_v1_00.tfrecord
2024-07-01 23:00:36   11711096 part-algo-2-amazon_reviews_us_Digital_Video_Games_v1_00.tfrecord

In [12]:
print(processed_validation_data_s3_uri)
!aws s3 ls $processed_validation_data_s3_uri/

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation
2024-07-01 23:00:11     582429 part-algo-1-amazon_reviews_us_Digital_Software_v1_00.tfrecord
2024-07-01 23:00:11     128035 part-algo-1-amazon_reviews_us_Gift_Card_v1_00.tfrecord
2024-07-01 23:00:36     651681 part-algo-2-amazon_reviews_us_Digital_Video_Games_v1_00.tfrecord

In [13]:
print(processed_test_data_s3_uri)
!aws s3 ls $processed_test_data_s3_uri/

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test
2024-07-01 23:00:11     582260 part-algo-1-amazon_reviews_us_Digital_Software_v1_00.tfrecord
2024-07-01 23:00:11     128809 part-algo-1-amazon_reviews_us_Gift_Card_v1_00.tfrecord
2024-07-01 23:00:37     650896 part-algo-2-amazon_reviews_us_Digital_Video_Games_v1_00.tfrecord

In [14]:
!pip list

WARNING: No metadata found in /opt/conda/lib/python3.10/site-packages
Package                               Version
------------------------------------- ----------------
absl-py                               2.1.0
accelerate                            0.21.0
aiobotocore                           2.12.2
aiohttp                               3.9.5
aioitertools                          0.11.0
aiosignal                             1.3.1
aiosqlite                             0.19.0
altair                                5.3.0
amazon-codewhisperer-jupyterlab-ext   2.0.2
amazon_sagemaker_jupyter_scheduler    3.0.11
amazon-sagemaker-sql-editor           0.1.7
amazon-sagemaker-sql-execution        0.1.5
amazon-sagemaker-sql-magic            0.1.1
annotated-types                       0.6.0
ansi2html                             0.0.0
ansicolors                            1.1.8
antlr4-python3-runtime                4.9.3
anyio                                 4.3.0
archspec                              0.2.3
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
arrow                                 1.3.0
asn1crypto                            1.5.1
astroid                               3.1.0
asttokens                             2.4.1
astunparse                            1.6.3
async-lru                             2.0.4
async-timeout                         4.0.3
attrs                                 23.2.0
autogluon                             0.8.3
autogluon.common                      0.8.3
autogluon.core                        0.8.3
autogluon.features                    0.8.3
autogluon.multimodal                  0.8.3
autogluon.tabular                     0.8.3
autogluon.timeseries                  0.8.3
autopep8                              2.0.4
autovizwidget                         0.21.0
aws-embedded-metrics                  3.2.0
aws-glue-sessions                     1.0.5
Babel                                 2.14.0
bcrypt                                4.1.2
beautifulsoup4                        4.12.3
binaryornot                           0.4.4
bleach                                6.1.0
blinker                               1.8.2
blis                                  0.7.10
boltons                               24.0.0
boto3                                 1.34.51
botocore                              1.34.51
Brotli                                1.1.0
cached-property                       1.5.2
cachetools                            5.3.3
catalogue                             2.0.10
catboost                              1.2.5
certifi                               2024.2.2
cffi                                  1.16.0
chardet                               5.2.0
charset-normalizer                    3.3.2
click                                 8.1.7
cloudpathlib                          0.16.0
cloudpickle                           2.2.1
colorama                              0.4.6
comm                                  0.2.2
conda                                 23.11.0
conda-libmamba-solver                 24.1.0
conda-package-handling                2.2.0
conda_package_streaming               0.9.0
confection                            0.1.4
contextlib2                           21.6.0
contourpy                             1.2.1
cookiecutter                          2.6.0
croniter                              1.4.1
cryptography                          42.0.7
cycler                                0.12.1
cymem                                 2.0.8
cytoolz                               0.12.3
dash                                  2.17.0
dask                                  2024.5.0
dataclasses                           0.8
dataclasses-json                      0.6.6
datasets                              2.19.1
debugpy                               1.8.1
decorator                             5.1.1
deepmerge                             1.1.1
defusedxml                            0.7.1
dill                                  0.3.8
diskcache                             5.6.3
distributed                           2024.5.0
distro                                1.9.0
docker                                7.0.0
docstring-to-markdown                 0.15
entrypoints                           0.4
evaluate                              0.4.1
exceptiongroup                        1.2.0
executing                             2.0.1
faiss                                 1.7.4
fastai                                2.7.15
fastapi                               0.110.3
fastcore                              1.5.35
fastdownload                          0.0.7
fastjsonschema                        2.19.1
fastprogress                          1.0.3
filelock                              3.14.0
flake8                                7.0.0
Flask                                 3.0.3
flatbuffers                           24.3.25
fonttools                             4.51.0
fqdn                                  1.5.1
frozenlist                            1.4.1
fsspec                                2023.6.0
future                                1.0.0
gast                                  0.5.4
gdown                                 5.2.0
gitdb                                 4.0.11
GitPython                             3.1.43
gluonts                               0.13.7
gmpy2                                 2.1.5
google-auth                           2.29.0
google-auth-oauthlib                  1.2.0
google-pasta                          0.2.0
graphviz                              0.20.3
greenlet                              3.0.3
grpcio                                1.59.3
gssapi                                1.8.3
h11                                   0.14.0
h2                                    4.1.0
h5py                                  3.11.0
hdijupyterutils                       0.21.0
hpack                                 4.0.0
httpcore                              1.0.5
httpx                                 0.27.0
huggingface_hub                       0.23.0
hyperframe                            6.0.1
idna                                  3.7
imagecodecs                           2024.1.1
imageio                               2.34.1
importlib-metadata                    6.10.0
importlib_resources                   6.4.0
ipykernel                             6.29.3
ipython                               8.24.0
ipywidgets                            8.1.2
isoduration                           20.11.0
isort                                 5.13.2
itsdangerous                          2.2.0
jedi                                  0.19.1
Jinja2                                3.1.4
jmespath                              1.0.1
joblib                                1.4.2
json5                                 0.9.25
jsonpatch                             1.33
jsonpath-ng                           1.6.1
jsonpointer                           2.4
jsonschema                            4.17.3
jupyter                               1.0.0
jupyter_ai                            2.15.0
jupyter_ai_magics                     2.15.0
jupyter_client                        8.6.1
jupyter_collaboration                 1.1.0
jupyter-console                       6.6.3
jupyter_core                          5.7.2
jupyter-dash                          0.4.2
jupyter-events                        0.6.3
jupyter-lsp                           2.2.5
jupyter_scheduler                     2.5.2
jupyter_server                        2.10.0
jupyter_server_fileid                 0.9.2
jupyter-server-mathjax                0.2.6
jupyter_server_proxy                  4.1.2
jupyter_server_terminals              0.5.3
jupyter-ydoc                          1.1.1
jupyterlab                            4.1.6
jupyterlab_git                        0.50.0
jupyterlab-lsp                        5.0.3
jupyterlab_pygments                   0.3.0
jupyterlab_server                     2.24.0
jupyterlab_widgets                    3.0.10
keras                                 2.15.0
kiwisolver                            1.4.5
krb5                                  0.5.1
langchain                             0.1.9
langchain-community                   0.0.38
langchain-core                        0.1.52
langcodes                             3.4.0
langsmith                             0.1.57
language_data                         1.2.0
libmambapy                            1.5.8
lightgbm                              3.3.5
lightning-utilities                   0.11.2
llvmlite                              0.42.0
locket                                1.0.0
lxml                                  4.9.4
marisa-trie                           1.1.0
Markdown                              3.6
markdown-it-py                        3.0.0
MarkupSafe                            2.1.5
marshmallow                           3.21.2
matplotlib                            3.8.4
matplotlib-inline                     0.1.7
mccabe                                0.7.0
mdurl                                 0.1.2
menuinst                              2.0.2
mistune                               3.0.2
ml-dtypes                             0.2.0
mlforecast                            0.7.3
mock                                  5.1.0
model-index                           0.1.11
mpmath                                1.3.0
msgpack                               1.0.7
multidict                             6.0.5
multiprocess                          0.70.16
munkres                               1.1.4
murmurhash                            1.0.10
mypy-extensions                       1.0.0
nbclient                              0.10.0
nbconvert                             7.16.4
nbdime                                4.0.1
nbformat                              5.10.4
nest_asyncio                          1.6.0
networkx                              3.3
nlpaug                                1.1.11
nltk                                  3.8.1
nose                                  1.3.7
notebook                              7.1.3
notebook_shim                         0.2.4
nptyping                              2.4.1
numba                                 0.59.1
numpy                                 1.26.4
oauthlib                              3.2.2
omegaconf                             2.2.3
openmim                               0.3.7
opt-einsum                            3.3.0
ordered-set                           4.1.0
orjson                                3.10.3
overrides                             7.7.0
packaging                             23.2
pandas                                2.1.4
pandocfilters                         1.5.0
papermill                             2.6.0
paramiko                              3.4.0
parso                                 0.8.4
partd                                 1.4.2
pathos                                0.3.2
pathy                                 0.10.2
patsy                                 0.5.6
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                10.3.0
pip                                   23.3.2
pkgutil_resolve_name                  1.3.10
platformdirs                          4.2.1
plotly                                5.22.0
pluggy                                1.5.0
ply                                   3.11
pox                                   0.3.4
ppft                                  1.7.6.8
preshed                               3.0.9
prometheus_client                     0.20.0
prompt-toolkit                        3.0.42
protobuf                              4.24.4
psutil                                5.9.8
ptyprocess                            0.7.0
pure-eval                             0.2.2
pure-sasl                             0.6.2
pyarrow                               15.0.0
pyarrow-hotfix                        0.6
pyasn1                                0.6.0
pyasn1_modules                        0.4.0
PyAthena                              3.8.2
pycodestyle                           2.11.1
pycosat                               0.6.6
pycparser                             2.22
pydantic                              1.10.14
pydantic_core                         2.18.1
pydocstyle                            6.3.0
pyflakes                              3.2.0
pyfunctional                          1.5.0
Pygments                              2.18.0
PyHive                                0.7.0
PyJWT                                 2.8.0
pylint                                3.1.1
PyNaCl                                1.5.0
pyOpenSSL                             24.0.0
pyparsing                             3.1.2
PyQt5                                 5.15.9
PyQt5-sip                             12.12.2
pyrsistent                            0.20.0
PySocks                               1.7.1
pyspnego                              0.10.2
pytesseract                           0.3.10
python-dateutil                       2.9.0
python-json-logger                    2.0.7
python-lsp-jsonrpc                    1.1.2
python-lsp-server                     1.11.0
python-slugify                        8.0.4
pytoolconfig                          1.2.5
pytorch-lightning                     2.0.9
pytorch-metric-learning               1.7.3
pytz                                  2023.3
pyu2f                                 0.1.5
PyWavelets                            1.4.1
PyYAML                                6.0.1
pyzmq                                 26.0.3
qtconsole                             5.5.2
QtPy                                  2.4.1
redshift_connector                    2.1.0
regex                                 2024.5.10
requests                              2.31.0
requests-kerberos                     0.14.0
requests-oauthlib                     2.0.0
responses                             0.18.0
retrying                              1.3.3
rfc3339-validator                     0.1.4
rfc3986-validator                     0.1.1
rich                                  13.7.1
rope                                  1.13.0
rsa                                   4.9
ruamel.yaml                           0.18.6
ruamel.yaml.clib                      0.2.8
s3fs                                  2024.6.1
s3transfer                            0.10.1
safetensors                           0.4.3
sagemaker                             2.219.0
sagemaker-headless-execution-driver   0.0.12
sagemaker-jupyterlab-emr-extension    0.1.9
sagemaker-jupyterlab-extension        0.3.2
sagemaker-jupyterlab-extension-common 0.1.15
sagemaker-kernel-wrapper              0.0.2
sagemaker-studio-analytics-extension  0.0.21
sagemaker-studio-sparkmagic-lib       0.1.4
sasl                                  0.3.1
schema                                0.7.7
scikit-image                          0.19.3
scikit-learn                          1.4.2
SciPy                                 1.11.4
scramp                                1.4.4
Send2Trash                            1.8.3
sentencepiece                         0.1.99
seqeval                               1.2.2
setuptools                            69.5.1
shellingham                           1.5.4
simpervisor                           1.0.0
sip                                   6.7.12
six                                   1.16.0
smart-open                            5.2.1
smclarify                             0.5
smdebug-rulesconfig                   1.0.1
smmap                                 5.0.0
sniffio                               1.3.1
snowballstemmer                       2.2.0
snowflake-connector-python            3.10.0
sortedcontainers                      2.4.0
soupsieve                             2.5
spacy                                 3.7.3
spacy-legacy                          3.0.12
spacy-loggers                         1.0.5
sparkmagic                            0.21.0
SQLAlchemy                            1.4.49
sqlparse                              0.4.4
srsly                                 2.4.8
stack-data                            0.6.2
starlette                             0.37.2
statsforecast                         1.4.0
statsmodels                           0.14.1
supervisor                            4.2.5
sympy                                 1.12
tabulate                              0.9.0
tblib                                 2.0.0
tenacity                              8.3.0
tensorboard                           2.15.2
tensorboard-data-server               0.7.0
tensorflow                            2.15.0
tensorflow_estimator                  2.15.0
termcolor                             2.4.0
terminado                             0.18.1
text-unidecode                        1.3
thinc                                 8.2.3
threadpoolctl                         3.5.0
thrift                                0.20.0
thrift-sasl                           0.4.3
tifffile                              2024.5.10
timm                                  0.9.16
tinycss2                              1.3.0
tokenizers                            0.19.1
toml                                  0.10.2
tomli                                 2.0.1
tomlkit                               0.12.5
toolz                                 0.12.1
torch                                 2.0.0.post104
torchmetrics                          1.0.3
torchvision                           0.15.2a0+ab7b3e6
tornado                               6.4
tqdm                                  4.66.4
traitlets                             5.14.3
transformers                          4.40.2
truststore                            0.8.0
typer                                 0.9.4
types-python-dateutil                 2.9.0.20240316
typing_extensions                     4.11.0
typing-inspect                        0.9.0
typing-utils                          0.1.0
typish                                1.9.3
tzdata                                2024.1
ujson                                 5.9.0
unicodedata2                          15.1.0
uri-template                          1.3.0
urllib3                               1.26.18
uvicorn                               0.29.0
wasabi                                1.1.2
wcwidth                               0.2.13
weasel                                0.3.4
webcolors                             1.13
webencodings                          0.5.1
websocket-client                      1.8.0
Werkzeug                              3.0.3
whatthepatch                          1.0.5
wheel                                 0.43.0
widgetsnbextension                    4.0.10
window_ops                            0.0.15
wrapt                                 1.14.1
xgboost                               1.7.6
xxhash                                3.4.1
y-py                                  0.6.2
yapf                                  0.40.1
yarl                                  1.9.4
ypy-websocket                         0.12.4
zict                                  3.0.0
zipp                                  3.17.0
zstandard                             0.22.0

In [15]:
from sagemaker.inputs import TrainingInput

s3_input_train_data = TrainingInput(s3_data=processed_train_data_s3_uri, distribution="ShardedByS3Key")
s3_input_validation_data = TrainingInput(s3_data=processed_validation_data_s3_uri, distribution="ShardedByS3Key")
s3_input_test_data = TrainingInput(s3_data=processed_test_data_s3_uri, distribution="ShardedByS3Key")

print(s3_input_train_data.config)
print(s3_input_validation_data.config)
print(s3_input_test_data.config)

{'DataSource': {'S3DataSource': {'S3DataType': 'S3Prefix', 'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train', 'S3DataDistributionType': 'ShardedByS3Key'}}}
{'DataSource': {'S3DataSource': {'S3DataType': 'S3Prefix', 'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation', 'S3DataDistributionType': 'ShardedByS3Key'}}}
{'DataSource': {'S3DataSource': {'S3DataType': 'S3Prefix', 'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test', 'S3DataDistributionType': 'ShardedByS3Key'}}}

In [16]:
!cat src/tf_bert_reviews.py

import time
import random
import pandas as pd
from glob import glob
import pprint
import argparse
import json
import subprocess
import sys
import os
import csv

# subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'tensorflow==2.1.0'])
import tensorflow as tf
import pandas as pd
import numpy as np

subprocess.check_call([sys.executable, "-m", "pip", "install", "transformers==3.5.1"])
# subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'sagemaker-tensorflow==2.1.0.1.0.0'])
# subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'smdebug==0.9.3'])
subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn==0.23.1"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib==3.2.1"])

from transformers import DistilBertTokenizer
from transformers import DistilBertConfig
from transformers import TFDistilBertForSequenceClassification

from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model


CLASSES = [1, 2, 3, 4, 5]


def select_data_and_label_from_record(record):
    x = {"input_ids": record["input_ids"], "input_mask": record["input_mask"], "segment_ids": record["segment_ids"]}

    y = record["label_ids"]

    return (x, y)


def file_based_input_dataset_builder(
    channel,
    input_filenames,
    pipe_mode,
    is_training,
    drop_remainder,
    batch_size,
    epochs,
    steps_per_epoch,
    max_seq_length,
):

    # For training, we want a lot of parallel reading and shuffling.
    # For eval, we want no shuffling and parallel reading doesn't matter.

    if pipe_mode:
        print("***** Using pipe_mode with channel {}".format(channel))
        from sagemaker_tensorflow import PipeModeDataset

        dataset = PipeModeDataset(channel=channel, record_format="TFRecord")
    else:
        print("***** Using input_filenames {}".format(input_filenames))
        dataset = tf.data.TFRecordDataset(input_filenames)

    dataset = dataset.repeat(epochs * steps_per_epoch * 100)
    #    dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)

    name_to_features = {
        "input_ids": tf.io.FixedLenFeature([max_seq_length], tf.int64),
        "input_mask": tf.io.FixedLenFeature([max_seq_length], tf.int64),
        "segment_ids": tf.io.FixedLenFeature([max_seq_length], tf.int64),
        "label_ids": tf.io.FixedLenFeature([], tf.int64),
    }

    def _decode_record(record, name_to_features):
        """Decodes a record to a TensorFlow example."""
        record = tf.io.parse_single_example(record, name_to_features)
        return record

    dataset = dataset.apply(
        tf.data.experimental.map_and_batch(
            lambda record: _decode_record(record, name_to_features),
            batch_size=batch_size,
            drop_remainder=drop_remainder,
            num_parallel_calls=tf.data.experimental.AUTOTUNE,
        )
    )

    #    dataset.cache()

    dataset = dataset.shuffle(buffer_size=1000, reshuffle_each_iteration=True)

    row_count = 0
    print("**************** {} *****************".format(channel))
    for row in dataset.as_numpy_iterator():
        print(row)
        if row_count == 5:
            break
        row_count = row_count + 1

    return dataset


def load_checkpoint_model(checkpoint_path):
    import glob
    import os

    glob_pattern = os.path.join(checkpoint_path, "*.h5")
    print("glob pattern {}".format(glob_pattern))

    list_of_checkpoint_files = glob.glob(glob_pattern)
    print("List of checkpoint files {}".format(list_of_checkpoint_files))

    latest_checkpoint_file = max(list_of_checkpoint_files)
    print("Latest checkpoint file {}".format(latest_checkpoint_file))

    initial_epoch_number_str = latest_checkpoint_file.rsplit("_", 1)[-1].split(".h5")[0]
    initial_epoch_number = int(initial_epoch_number_str)

    loaded_model = TFDistilBertForSequenceClassification.from_pretrained(latest_checkpoint_file, config=config)

    print("loaded_model {}".format(loaded_model))
    print("initial_epoch_number {}".format(initial_epoch_number))

    return loaded_model, initial_epoch_number


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--train_data", type=str, default=os.environ["SM_CHANNEL_TRAIN"])
    parser.add_argument("--validation_data", type=str, default=os.environ["SM_CHANNEL_VALIDATION"])
    parser.add_argument("--test_data", type=str, default=os.environ["SM_CHANNEL_TEST"])
    parser.add_argument("--output_dir", type=str, default=os.environ["SM_OUTPUT_DIR"])
    parser.add_argument("--hosts", type=list, default=json.loads(os.environ["SM_HOSTS"]))
    parser.add_argument("--current_host", type=str, default=os.environ["SM_CURRENT_HOST"])
    parser.add_argument("--num_gpus", type=int, default=os.environ["SM_NUM_GPUS"])
    parser.add_argument("--checkpoint_base_path", type=str, default="/opt/ml/checkpoints")
    parser.add_argument("--use_xla", type=eval, default=False)
    parser.add_argument("--use_amp", type=eval, default=False)
    parser.add_argument("--max_seq_length", type=int, default=64)
    parser.add_argument("--train_batch_size", type=int, default=128)
    parser.add_argument("--validation_batch_size", type=int, default=256)
    parser.add_argument("--test_batch_size", type=int, default=256)
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--learning_rate", type=float, default=0.00003)
    parser.add_argument("--epsilon", type=float, default=0.00000001)
    parser.add_argument("--train_steps_per_epoch", type=int, default=None)
    parser.add_argument("--validation_steps", type=int, default=None)
    parser.add_argument("--test_steps", type=int, default=None)
    parser.add_argument("--freeze_bert_layer", type=eval, default=False)
    parser.add_argument("--enable_sagemaker_debugger", type=eval, default=False)
    parser.add_argument("--run_validation", type=eval, default=False)
    parser.add_argument("--run_test", type=eval, default=False)
    parser.add_argument("--run_sample_predictions", type=eval, default=False)
    parser.add_argument("--enable_tensorboard", type=eval, default=False)
    parser.add_argument("--enable_checkpointing", type=eval, default=False)
    parser.add_argument("--output_data_dir", type=str, default=os.environ["SM_OUTPUT_DATA_DIR"])  # This is unused

    # This points to the S3 location - this should not be used by our code
    # We should use /opt/ml/model/ instead
    # parser.add_argument('--model_dir',
    #                     type=str,
    #                     default=os.environ['SM_MODEL_DIR'])

    args, _ = parser.parse_known_args()
    print("Args:")
    print(args)

    env_var = os.environ
    print("Environment Variables:")
    pprint.pprint(dict(env_var), width=1)

    print("SM_TRAINING_ENV {}".format(env_var["SM_TRAINING_ENV"]))
    sm_training_env_json = json.loads(env_var["SM_TRAINING_ENV"])
    is_master = sm_training_env_json["is_master"]
    print("is_master {}".format(is_master))

    train_data = args.train_data
    print("train_data {}".format(train_data))
    validation_data = args.validation_data
    print("validation_data {}".format(validation_data))
    test_data = args.test_data
    print("test_data {}".format(test_data))
    local_model_dir = os.environ["SM_MODEL_DIR"]
    output_dir = args.output_dir
    print("output_dir {}".format(output_dir))
    hosts = args.hosts
    print("hosts {}".format(hosts))
    current_host = args.current_host
    print("current_host {}".format(current_host))
    num_gpus = args.num_gpus
    print("num_gpus {}".format(num_gpus))
    job_name = os.environ["SAGEMAKER_JOB_NAME"]
    print("job_name {}".format(job_name))
    use_xla = args.use_xla
    print("use_xla {}".format(use_xla))
    use_amp = args.use_amp
    print("use_amp {}".format(use_amp))
    max_seq_length = args.max_seq_length
    print("max_seq_length {}".format(max_seq_length))
    train_batch_size = args.train_batch_size
    print("train_batch_size {}".format(train_batch_size))
    validation_batch_size = args.validation_batch_size
    print("validation_batch_size {}".format(validation_batch_size))
    test_batch_size = args.test_batch_size
    print("test_batch_size {}".format(test_batch_size))
    epochs = args.epochs
    print("epochs {}".format(epochs))
    learning_rate = args.learning_rate
    print("learning_rate {}".format(learning_rate))
    epsilon = args.epsilon
    print("epsilon {}".format(epsilon))
    train_steps_per_epoch = args.train_steps_per_epoch
    print("train_steps_per_epoch {}".format(train_steps_per_epoch))
    validation_steps = args.validation_steps
    print("validation_steps {}".format(validation_steps))
    test_steps = args.test_steps
    print("test_steps {}".format(test_steps))
    freeze_bert_layer = args.freeze_bert_layer
    print("freeze_bert_layer {}".format(freeze_bert_layer))
    enable_sagemaker_debugger = args.enable_sagemaker_debugger
    print("enable_sagemaker_debugger {}".format(enable_sagemaker_debugger))
    run_validation = args.run_validation
    print("run_validation {}".format(run_validation))
    run_test = args.run_test
    print("run_test {}".format(run_test))
    run_sample_predictions = args.run_sample_predictions
    print("run_sample_predictions {}".format(run_sample_predictions))
    enable_tensorboard = args.enable_tensorboard
    print("enable_tensorboard {}".format(enable_tensorboard))
    enable_checkpointing = args.enable_checkpointing
    print("enable_checkpointing {}".format(enable_checkpointing))

    checkpoint_base_path = args.checkpoint_base_path
    print("checkpoint_base_path {}".format(checkpoint_base_path))

    if is_master:
        checkpoint_path = checkpoint_base_path
    else:
        checkpoint_path = "/tmp/checkpoints"
    print("checkpoint_path {}".format(checkpoint_path))

    # Determine if PipeMode is enabled
    pipe_mode_str = os.environ.get("SM_INPUT_DATA_CONFIG", "")
    pipe_mode = pipe_mode_str.find("Pipe") >= 0
    print("Using pipe_mode: {}".format(pipe_mode))

    # Model Output
    transformer_fine_tuned_model_path = os.path.join(local_model_dir, "transformers/fine-tuned/")
    os.makedirs(transformer_fine_tuned_model_path, exist_ok=True)

    # SavedModel Output
    tensorflow_saved_model_path = os.path.join(local_model_dir, "tensorflow/saved_model/0")
    os.makedirs(tensorflow_saved_model_path, exist_ok=True)

    # Tensorboard Logs
    tensorboard_logs_path = os.path.join(local_model_dir, "tensorboard/")
    os.makedirs(tensorboard_logs_path, exist_ok=True)

    # Commented out due to incompatibility with transformers library (possibly)
    # Set the global precision mixed_precision policy to "mixed_float16"
    #    mixed_precision_policy = 'mixed_float16'
    #    print('Mixed precision policy {}'.format(mixed_precision_policy))
    #    policy = mixed_precision.Policy(mixed_precision_policy)
    #    mixed_precision.set_policy(policy)

    distributed_strategy = tf.distribute.MirroredStrategy()
    # Comment out when using smdebug as smdebug does not support MultiWorkerMirroredStrategy() as of smdebug 0.8.0
    # distributed_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    with distributed_strategy.scope():
        tf.config.optimizer.set_jit(use_xla)
        tf.config.optimizer.set_experimental_options({"auto_mixed_precision": use_amp})

        train_data_filenames = glob(os.path.join(train_data, "*.tfrecord"))
        print("train_data_filenames {}".format(train_data_filenames))
        train_dataset = file_based_input_dataset_builder(
            channel="train",
            input_filenames=train_data_filenames,
            pipe_mode=pipe_mode,
            is_training=True,
            drop_remainder=False,
            batch_size=train_batch_size,
            epochs=epochs,
            steps_per_epoch=train_steps_per_epoch,
            max_seq_length=max_seq_length,
        ).map(select_data_and_label_from_record)

        tokenizer = None
        config = None
        model = None
        transformer_model = None

        # This is required when launching many instances at once...  the urllib request seems to get denied periodically
        successful_download = False
        retries = 0
        while retries < 5 and not successful_download:
            try:
                tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
                config = DistilBertConfig.from_pretrained(
                    "distilbert-base-uncased",
                    num_labels=len(CLASSES),
                    id2label={0: 1, 1: 2, 2: 3, 3: 4, 4: 5},
                    label2id={1: 0, 2: 1, 3: 2, 4: 3, 5: 4},
                )

                transformer_model = TFDistilBertForSequenceClassification.from_pretrained(
                    "distilbert-base-uncased", config=config
                )

                input_ids = tf.keras.layers.Input(shape=(max_seq_length,), name="input_ids", dtype="int32")
                input_mask = tf.keras.layers.Input(shape=(max_seq_length,), name="input_mask", dtype="int32")

                embedding_layer = transformer_model.distilbert(input_ids, attention_mask=input_mask)[0]
                X = tf.keras.layers.Bidirectional(
                    tf.keras.layers.LSTM(50, return_sequences=True, dropout=0.1, recurrent_dropout=0.1)
                )(embedding_layer)
                X = tf.keras.layers.GlobalMaxPool1D()(X)
                X = tf.keras.layers.Dense(50, activation="relu")(X)
                X = tf.keras.layers.Dropout(0.2)(X)
                X = tf.keras.layers.Dense(len(CLASSES), activation="softmax")(X)

                model = tf.keras.Model(inputs=[input_ids, input_mask], outputs=X)

                for layer in model.layers[:3]:
                    layer.trainable = not freeze_bert_layer

                successful_download = True
                print("Sucessfully downloaded after {} retries.".format(retries))
            except:
                retries = retries + 1
                random_sleep = random.randint(1, 30)
                print("Retry #{}.  Sleeping for {} seconds".format(retries, random_sleep))
                time.sleep(random_sleep)

        callbacks = []

        initial_epoch_number = 0

        if enable_checkpointing:
            print("***** Checkpoint enabled *****")

            os.makedirs(checkpoint_path, exist_ok=True)
            if os.listdir(checkpoint_path):
                print("***** Found checkpoint *****")
                print(checkpoint_path)
                model, initial_epoch_number = load_checkpoint_model(checkpoint_path)
                print("***** Using checkpoint model {} *****".format(model))

            checkpoint_callback = ModelCheckpoint(
                filepath=os.path.join(checkpoint_path, "tf_model_{epoch:05d}.h5"),
                save_weights_only=False,
                verbose=1,
                monitor="val_accuracy",
            )
            print("*** CHECKPOINT CALLBACK {} ***".format(checkpoint_callback))
            callbacks.append(checkpoint_callback)

        if not tokenizer or not model or not config:
            print("Not properly initialized...")

        optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate, epsilon=epsilon)
        print("** use_amp {}".format(use_amp))
        if use_amp:
            # loss scaling is currently required when using mixed precision
            optimizer = tf.keras.mixed_precision.experimental.LossScaleOptimizer(optimizer, "dynamic")

        print("enable_sagemaker_debugger {}".format(enable_sagemaker_debugger))
        if enable_sagemaker_debugger:
            print("*** DEBUGGING ***")
            import smdebug.tensorflow as smd

            # This assumes that we specified debugger_hook_config
            debugger_callback = smd.KerasHook.create_from_json_file()
            print("*** DEBUGGER CALLBACK {} ***".format(debugger_callback))
            callbacks.append(debugger_callback)
            optimizer = debugger_callback.wrap_optimizer(optimizer)

        if enable_tensorboard:
            tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=tensorboard_logs_path)
            print("*** TENSORBOARD CALLBACK {} ***".format(tensorboard_callback))
            callbacks.append(tensorboard_callback)

        print("*** OPTIMIZER {} ***".format(optimizer))

        loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
        metric = tf.keras.metrics.SparseCategoricalAccuracy("accuracy")

        model.compile(optimizer=optimizer, loss=loss, metrics=[metric])
        print("Compiled model {}".format(model))
        #        model.layers[0].trainable = not freeze_bert_layer
        print(model.summary())

        if run_validation:
            validation_data_filenames = glob(os.path.join(validation_data, "*.tfrecord"))
            print("validation_data_filenames {}".format(validation_data_filenames))
            validation_dataset = file_based_input_dataset_builder(
                channel="validation",
                input_filenames=validation_data_filenames,
                pipe_mode=pipe_mode,
                is_training=False,
                drop_remainder=False,
                batch_size=validation_batch_size,
                epochs=epochs,
                steps_per_epoch=validation_steps,
                max_seq_length=max_seq_length,
            ).map(select_data_and_label_from_record)

            print("Starting Training and Validation...")
            validation_dataset = validation_dataset.take(validation_steps)
            train_and_validation_history = model.fit(
                train_dataset,
                shuffle=True,
                epochs=epochs,
                initial_epoch=initial_epoch_number,
                steps_per_epoch=train_steps_per_epoch,
                validation_data=validation_dataset,
                validation_steps=validation_steps,
                callbacks=callbacks,
            )
            print(train_and_validation_history)
        else:  # Not running validation
            print("Starting Training (Without Validation)...")
            train_history = model.fit(
                train_dataset,
                shuffle=True,
                epochs=epochs,
                initial_epoch=initial_epoch_number,
                steps_per_epoch=train_steps_per_epoch,
                callbacks=callbacks,
            )
            print(train_history)

        if run_test:
            test_data_filenames = glob(os.path.join(test_data, "*.tfrecord"))
            print("test_data_filenames {}".format(test_data_filenames))
            test_dataset = file_based_input_dataset_builder(
                channel="test",
                input_filenames=test_data_filenames,
                pipe_mode=pipe_mode,
                is_training=False,
                drop_remainder=False,
                batch_size=test_batch_size,
                epochs=epochs,
                steps_per_epoch=test_steps,
                max_seq_length=max_seq_length,
            ).map(select_data_and_label_from_record)

            print("Starting test...")
            test_history = model.evaluate(test_dataset, steps=test_steps, callbacks=callbacks)

            print("Test history {}".format(test_history))

        # Save the Fine-Yuned Transformers Model as a New "Pre-Trained" Model
        print("transformer_fine_tuned_model_path {}".format(transformer_fine_tuned_model_path))
        transformer_model.save_pretrained(transformer_fine_tuned_model_path)
        print("Model inputs after save_pretrained: {}".format(model.inputs))

        # Save the TensorFlow SavedModel for Serving Predictions
        print("tensorflow_saved_model_path {}".format(tensorflow_saved_model_path))
        model.save(tensorflow_saved_model_path, include_optimizer=False, overwrite=True, save_format="tf")

        # Copy inference.py and requirements.txt to the code/ directory

# Setup Static Hyper-Parameters for Classification Layer
First, retrieve `max_seq_length` from the prepare phase.

In [17]:
%store -r max_seq_length

In [18]:
try:
    max_seq_length
    print("[OK]")
except NameError:
    print("+++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the PREPARE section before you continue.")
    print("+++++++++++++++++++++++++++++++")

[OK]

In [19]:
print(max_seq_length)

64

In [20]:
epochs = 3
epsilon = 0.00000001
validation_batch_size = 128
test_batch_size = 128
train_steps_per_epoch = 100
validation_steps = 100
test_steps = 100
train_instance_count = 1
train_instance_type = "ml.m5.xlarge"  # evt
# train_instance_type='ml.m5.4xlarge' #bur
train_volume_size = 1024
use_xla = True
use_amp = True
enable_sagemaker_debugger = False
enable_checkpointing = False
enable_tensorboard = False
input_mode = "File"
run_validation = True
run_test = True
run_sample_predictions = True

# Track the Optimizations Within our Experiment

In [21]:
%store -r experiment_name

In [22]:
try:
    experiment_name
    print("[OK]")
except NameError:
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the TRAIN section before you continue.")
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

[OK]

In [23]:
print(experiment_name)

Amazon-Customer-Reviews-BERT-Experiment-1719873607

In [24]:
%store -r trial_name

In [25]:
try:
    trial_name
    print("[OK]")
except NameError:
    print("+++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the previous TRAIN section before you continue.")
    print("+++++++++++++++++++++++++++++++")

[OK]

In [26]:
print(trial_name)

trial-1719873613

In [28]:
!pip install sagemaker-experiments

Collecting sagemaker-experiments
  Using cached sagemaker_experiments-0.1.45-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: boto3>=1.16.27 in /opt/conda/lib/python3.10/site-packages (from sagemaker-experiments) (1.34.51)
Requirement already satisfied: botocore<1.35.0,>=1.34.51 in /opt/conda/lib/python3.10/site-packages (from boto3>=1.16.27->sagemaker-experiments) (1.34.51)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3>=1.16.27->sagemaker-experiments) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /opt/conda/lib/python3.10/site-packages (from boto3>=1.16.27->sagemaker-experiments) (0.10.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.10/site-packages (from botocore<1.35.0,>=1.34.51->boto3>=1.16.27->sagemaker-experiments) (2.9.0)
Requirement already satisfied: urllib3<2.1,>=1.25.4 in /opt/conda/lib/python3.10/site-packages (from botocore<1.35.0,>=1.34.51->boto3>=1.16.27->sagemaker-experiments) (1.26.18)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.35.0,>=1.34.51->boto3>=1.16.27->sagemaker-experiments) (1.16.0)
Using cached sagemaker_experiments-0.1.45-py3-none-any.whl (42 kB)
WARNING: Error parsing requirements for fsspec: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/fsspec-2023.6.0.dist-info/METADATA'
Installing collected packages: sagemaker-experiments
Successfully installed sagemaker-experiments-0.1.45

In [29]:
import time
from smexperiments.trial import Trial

timestamp = "{}".format(int(time.time()))

trial = Trial.load(trial_name=trial_name)
print(trial)

Trial(sagemaker_boto_client=<botocore.client.SageMaker object at 0x7fa277d69450>,trial_name='trial-1719873613',trial_arn='arn:aws:sagemaker:us-east-1:891377026966:experiment-trial/trial-1719873613',display_name='trial-1719873613',experiment_name='Amazon-Customer-Reviews-BERT-Experiment-1719873607',creation_time=datetime.datetime(2024, 7, 1, 22, 40, 13, 898000, tzinfo=tzlocal()),created_by={'UserProfileArn': 'arn:aws:sagemaker:us-east-1:891377026966:user-profile/d-fu4acyc03cpg/default-20240628T190970', 'UserProfileName': 'default-20240628T190970', 'DomainId': 'd-fu4acyc03cpg'},last_modified_time=datetime.datetime(2024, 7, 2, 18, 58, 1, 719000, tzinfo=tzlocal()),last_modified_by={},response_metadata={'RequestId': '3624b7fd-bb2b-4b94-9b16-b66a23a21966', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '3624b7fd-bb2b-4b94-9b16-b66a23a21966', 'content-type': 'application/x-amz-json-1.1', 'content-length': '509', 'date': 'Tue, 02 Jul 2024 22:44:21 GMT'}, 'RetryAttempts': 0})

In [30]:
from smexperiments.tracker import Tracker

tracker_optimize = Tracker.create(display_name="optimize-1", sagemaker_boto_client=sm)

optimize_trial_component_name = tracker_optimize.trial_component.trial_component_name
print("Optimize trial component name {}".format(optimize_trial_component_name))

Optimize trial component name TrialComponent-2024-07-02-224426693344-vnzt

# Attach the `deploy` Trial Component and Tracker as a Component to the Trial

In [31]:
trial.add_trial_component(tracker_optimize.trial_component)

# Setup Dynamic Hyper-Parameter Ranges to Explore

In [32]:
from sagemaker.tuner import IntegerParameter
from sagemaker.tuner import ContinuousParameter
from sagemaker.tuner import CategoricalParameter
from sagemaker.tuner import HyperparameterTuner

hyperparameter_ranges = {
    "learning_rate": ContinuousParameter(0.00001, 0.00005, scaling_type="Linear"),
    "train_batch_size": CategoricalParameter([128, 256]),
    "freeze_bert_layer": CategoricalParameter([True, False]),
}

# Setup Metrics

In [33]:
metrics_definitions = [
    {"Name": "train:loss", "Regex": "loss: ([0-9\\.]+)"},
    {"Name": "train:accuracy", "Regex": "accuracy: ([0-9\\.]+)"},
    {"Name": "validation:loss", "Regex": "val_loss: ([0-9\\.]+)"},
    {"Name": "validation:accuracy", "Regex": "val_accuracy: ([0-9\\.]+)"},
]

In [34]:
from sagemaker.tensorflow import TensorFlow

estimator = TensorFlow(
    entry_point="tf_bert_reviews.py",
    source_dir="src",
    role=role,
    instance_count=train_instance_count,
    instance_type=train_instance_type,
    volume_size=train_volume_size,
    py_version="py37",
    framework_version="2.3.1",
    hyperparameters={
        "epochs": epochs,
        "epsilon": epsilon,
        "validation_batch_size": validation_batch_size,
        "test_batch_size": test_batch_size,
        "train_steps_per_epoch": train_steps_per_epoch,
        "validation_steps": validation_steps,
        "test_steps": test_steps,
        "use_xla": use_xla,
        "use_amp": use_amp,
        "max_seq_length": max_seq_length,
        "enable_sagemaker_debugger": enable_sagemaker_debugger,
        "enable_checkpointing": enable_checkpointing,
        "enable_tensorboard": enable_tensorboard,
        "run_validation": run_validation,
        "run_test": run_test,
        "run_sample_predictions": run_sample_predictions,
    },
    input_mode=input_mode,
    metric_definitions=metrics_definitions,
    #                       max_run=7200 # max 2 hours * 60 minutes seconds per hour * 60 seconds per minute
)

# Setup HyperparameterTuner with Estimator and Hyper-Parameter Ranges

In [35]:
objective_metric_name = "train:accuracy"

tuner = HyperparameterTuner(
    estimator=estimator,
    objective_type="Maximize",
    objective_metric_name=objective_metric_name,
    hyperparameter_ranges=hyperparameter_ranges,
    metric_definitions=metrics_definitions,
    max_jobs=2,
    max_parallel_jobs=1,
    strategy="Bayesian",
    early_stopping_type="Auto",
)

# Start Tuning Job

In [36]:
tuner.fit(
    inputs={"train": s3_input_train_data, "validation": s3_input_validation_data, "test": s3_input_test_data},
    include_cls_metadata=False,
    wait=False,
)

INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
WARNING:sagemaker.estimator:No finished training job found associated with this estimator. Please make sure this estimator is only used for building workflow config
WARNING:sagemaker.estimator:No finished training job found associated with this estimator. Please make sure this estimator is only used for building workflow config
INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
INFO:sagemaker:Creating hyperparameter tuning job with name: tensorflow-training-240702-2245

# Check Tuning Job Status
Re-run this cell to track the status.

In [37]:
from pprint import pprint

tuning_job_name = tuner.latest_tuning_job.job_name

In [38]:
from IPython.core.display import display, HTML

display(
    HTML(
        '<b>Review <a target="blank" href="https://console.aws.amazon.com/sagemaker/home?region={}#/hyper-tuning-jobs/{}">Hyper-Parameter Tuning Job</a></b>'.format(
            region, tuning_job_name
        )
    )
)

/tmp/ipykernel_2449/399046009.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

# _Please Wait for the ^^ Tuning Job ^^ to Complete Above_

In [39]:
%%time

tuner.wait()

.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................!
CPU times: user 5.79 s, sys: 548 ms, total: 6.34 s
Wall time: 1h 47min 49s

# [INFO] _Feel free to continue to the next workshop section while this notebook is running._

# Show the Tuning Job
### _Note:  This will fail at first.  Please wait about 15-30 seconds and re-run._

In [40]:
from sagemaker.analytics import HyperparameterTuningJobAnalytics

hp_results = HyperparameterTuningJobAnalytics(sagemaker_session=sess, hyperparameter_tuning_job_name=tuning_job_name)

df_results = hp_results.dataframe()
df_results.shape

(2, 9)

In [41]:
df_results.sort_values("FinalObjectiveValue", ascending=0)

,freeze_bert_layer,learning_rate,train_batch_size,TrainingJobName,TrainingJobStatus,FinalObjectiveValue,TrainingStartTime,TrainingEndTime,TrainingElapsedTimeSeconds
1,"""False""",0.000042,"""128""",tensorflow-training-240702-2245-001-0ab8e046,Completed,0.4837,2024-07-02 22:45:53+00:00,2024-07-03 00:14:58+00:00,5345.0
0,"""True""",0.000029,"""128""",tensorflow-training-240702-2245-002-54822820,Stopped,0.3125,2024-07-03 00:15:44+00:00,2024-07-03 00:30:56+00:00,912.0

# Show the Best Candidate

In [42]:
df_results.sort_values("FinalObjectiveValue", ascending=0).head(1)

,freeze_bert_layer,learning_rate,train_batch_size,TrainingJobName,TrainingJobStatus,FinalObjectiveValue,TrainingStartTime,TrainingEndTime,TrainingElapsedTimeSeconds
1,"""False""",0.000042,"""128""",tensorflow-training-240702-2245-001-0ab8e046,Completed,0.4837,2024-07-02 22:45:53+00:00,2024-07-03 00:14:58+00:00,5345.0

# Log the Best Hyper-Parameter and Objective Metric in the Experiment

Logging `learning_rate` parameter and `accuracy` metric

In [43]:
best_learning_rate = df_results.sort_values("FinalObjectiveValue", ascending=0).head(1)["learning_rate"]
print(best_learning_rate)

1    0.000042
Name: learning_rate, dtype: float64

In [44]:
best_accuracy = df_results.sort_values("FinalObjectiveValue", ascending=0).head(1)["FinalObjectiveValue"]
print(best_accuracy)

1    0.4837
Name: FinalObjectiveValue, dtype: float64

In [45]:
tracker_optimize.log_parameters({"learning_rate": float(best_learning_rate)})

# must save after logging
tracker_optimize.trial_component.save()

/tmp/ipykernel_2449/3757020509.py:1: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  tracker_optimize.log_parameters({"learning_rate": float(best_learning_rate)})

TrialComponent(sagemaker_boto_client=<botocore.client.SageMaker object at 0x7fa2798e8b80>,trial_component_name='TrialComponent-2024-07-02-224426693344-vnzt',display_name='optimize-1',tags=None,trial_component_arn='arn:aws:sagemaker:us-east-1:891377026966:experiment-trial-component/TrialComponent-2024-07-02-224426693344-vnzt',response_metadata={'RequestId': 'e74708cf-4249-4ed4-a3cf-c4e5cd57b5f8', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'e74708cf-4249-4ed4-a3cf-c4e5cd57b5f8', 'content-type': 'application/x-amz-json-1.1', 'content-length': '135', 'date': 'Wed, 03 Jul 2024 00:50:51 GMT'}, 'RetryAttempts': 0},parameters={'learning_rate': 4.184158274319715e-05},input_artifacts={},output_artifacts={})

In [46]:
tracker_optimize.log_metric("accuracy", float(best_accuracy))

# must save after logging
tracker_optimize.trial_component.save()

/tmp/ipykernel_2449/312790556.py:1: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  tracker_optimize.log_metric("accuracy", float(best_accuracy))
WARNING:root:Cannot write metrics in this environment.

TrialComponent(sagemaker_boto_client=<botocore.client.SageMaker object at 0x7fa2798e8b80>,trial_component_name='TrialComponent-2024-07-02-224426693344-vnzt',display_name='optimize-1',tags=None,trial_component_arn='arn:aws:sagemaker:us-east-1:891377026966:experiment-trial-component/TrialComponent-2024-07-02-224426693344-vnzt',response_metadata={'RequestId': 'bb066e3c-c6f1-4c29-9d34-5e73e7789f76', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'bb066e3c-c6f1-4c29-9d34-5e73e7789f76', 'content-type': 'application/x-amz-json-1.1', 'content-length': '135', 'date': 'Wed, 03 Jul 2024 00:50:54 GMT'}, 'RetryAttempts': 0},parameters={'learning_rate': 4.184158274319715e-05},input_artifacts={},output_artifacts={})

# Show Experiment Analytics

In [47]:
from sagemaker.analytics import ExperimentAnalytics

lineage_table = ExperimentAnalytics(
    sagemaker_session=sess,
    experiment_name=experiment_name,
    metric_names=["validation:accuracy"],
    sort_by="CreationTime",
    sort_order="Descending",
)

df_lineage = lineage_table.dataframe()
df_lineage.shape

(4, 71)

In [48]:
df_lineage

,TrialComponentName,DisplayName,learning_rate,Trials,Experiments,SourceArn,SageMaker.InstanceCount,SageMaker.InstanceType,SageMaker.VolumeSizeInGB,SageMaker.ImageUri - MediaType,...,SageMaker.ModelArtifact - Value,AWS_DEFAULT_REGION,raw-input-data - MediaType,raw-input-data - Value,bert-test - MediaType,bert-test - Value,bert-train - MediaType,bert-train - Value,bert-validation - MediaType,bert-validation - Value
0,TrialComponent-2024-07-02-224426693344-vnzt,optimize-1,0.000042,[trial-1719873613],[Amazon-Customer-Reviews-BERT-Experiment-17198...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sagemaker-scikit-learn-2024-07-02-18-40-05-240...,evaluate,NaN,[trial-1719873613],[Amazon-Customer-Reviews-BERT-Experiment-17198...,arn:aws:sagemaker:us-east-1:891377026966:proce...,1.0,ml.t3.xlarge,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tensorflow-training-2024-07-02-02-08-36-935-aw...,train,0.000010,[trial-1719873613],[Amazon-Customer-Reviews-BERT-Experiment-17198...,arn:aws:sagemaker:us-east-1:891377026966:train...,1.0,ml.c5.4xlarge,1024.0,NaN,...,s3://sagemaker-us-east-1-891377026966/tensorfl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sagemaker-scikit-learn-2024-07-01-22-42-17-522...,prepare,NaN,[trial-1719873613],[Amazon-Customer-Reviews-BERT-Experiment-17198...,arn:aws:sagemaker:us-east-1:891377026966:proce...,2.0,ml.t3.xlarge,30.0,NaN,...,NaN,us-east-1,NaN,s3://sagemaker-us-east-1-891377026966/amazon-r...,NaN,s3://sagemaker-us-east-1-891377026966/sagemake...,NaN,s3://sagemaker-us-east-1-891377026966/sagemake...,NaN,s3://sagemaker-us-east-1-891377026966/sagemake...

# Pass `tuning_job_name` to the Next Notebook

In [49]:
print(tuning_job_name)

tensorflow-training-240702-2245

In [50]:
%store tuning_job_name

Stored 'tuning_job_name' (str)

In [51]:
%store

Stored variables and their in-db values:
balance_dataset                                       -> True
balanced_bias_data_jsonlines_s3_uri                   -> 's3://sagemaker-us-east-1-891377026966/bias-detect
balanced_bias_data_s3_uri                             -> 's3://sagemaker-us-east-1-891377026966/bias-detect
bias_data_s3_uri                                      -> 's3://sagemaker-us-east-1-891377026966/bias-detect
experiment_name                                       -> 'Amazon-Customer-Reviews-BERT-Experiment-171987360
feature_group_name                                    -> 'reviews-feature-group-1719873648'
feature_store_offline_prefix                          -> 'reviews-feature-store-1719873648'
ingest_create_athena_db_passed                        -> True
ingest_create_athena_table_parquet_passed             -> True
ingest_create_athena_table_tsv_passed                 -> True
max_seq_length                                        -> 64
processed_metrics_s3_uri                              -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
processed_test_data_s3_uri                            -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
processed_train_data_s3_uri                           -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
processed_validation_data_s3_uri                      -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
processing_evaluation_metrics_job_name                -> 'sagemaker-scikit-learn-2024-07-02-18-40-05-240'
raw_input_data_s3_uri                                 -> 's3://sagemaker-us-east-1-891377026966/amazon-revi
s3_private_path_tsv                                   -> 's3://sagemaker-us-east-1-891377026966/amazon-revi
s3_public_path_tsv                                    -> 's3://dsoaws/amazon-reviews-pds/tsv'
test_data_bias_s3_uri                                 -> 's3://sagemaker-us-east-1-891377026966/bias/test_d
test_data_explainablity_s3_uri                        -> 's3://sagemaker-us-east-1-891377026966/bias/test_d
test_split_percentage                                 -> 0.05
train_split_percentage                                -> 0.9
training_job_name                                     -> 'tensorflow-training-2024-07-02-02-08-36-935'
trial_name                                            -> 'trial-1719873613'
tuning_job_name                                       -> 'tensorflow-training-240702-2245'
validation_split_percentage                           -> 0.05

# Release Resources

In [52]:
%%html

<p><b>Shutting down your kernel for this notebook to release resources.</b></p>
<button class="sm-command-button" data-commandlinker-command="kernelmenu:shutdown" style="display:none;">Shutdown Kernel</button>
        
<script>
try {
    els = document.getElementsByClassName("sm-command-button");
    els[0].click();
}
catch(err) {
    // NoOp
}    
</script>

In [ ]:
%%javascript

try {
    Jupyter.notebook.save_checkpoint();
    Jupyter.notebook.session.delete();
}
catch(err) {
    // NoOp
}